### ISSUE TITLE
Scale Down Images in HTML Reports for Better Readability and Layout

### ISSUE THREAD

**Issue by takahirom** [takahirom/roborazzi#157]
I propose that the images be displayed at a scaled-down size in the HTML report. Additionally, clicking on the scaled-down image should display the image in its original size for closer inspection.

https://github.com/takahirom/roborazzi/issues/153#issuecomment-1722303954
https://github.com/takahirom/roborazzi/commit/7154c28ce3c13a800f2fe71b966440a8cdd2e3ae#diff-166296446cdf658776b268ea279e13e37f7f2aba3177a85a5ba298a94b8f1d44R36

**Comment by takahirom** [comment]
Maybe we can use `modals` to display the image
https://materializeweb.com/modals.html

**Comment by jeprubio** [comment]
I've tried that but it didn't look good: https://www.youtube.com/watch?v=-jaBaPttxa0
The code I had: https://github.com/jeprubio/roborazzi/tree/jep/show-images-in-modal

Basically it has a single modal and via javascript the on click of each image is set so that when an image is clicked it gets the info of that image and set it on the modal.

Perhaps I did something wrong or there is a better way.

**Comment by takahirom** [comment]
@jeprubio 
The modal bottom sheet looks great!

**Comment by jeprubio** [comment]
OK, I've just created a PR with that change https://github.com/takahirom/roborazzi/pull/169

**Comment by takahirom** [comment]
I think this is solved now. Thanks!
