### ISSUE TITLE
Tests still pass after changing composable

### ISSUE THREAD

**Issue by tomcully** [takahirom/roborazzi#179]
I've been using the Roborazzi testing library and noticed that it's possible to have tests pass even though the images being compared are quite different.

By updating the captureComposeLambdaImage test to wrap the Text composable in a Box with a more controlled size, when I recorded the screenshots for future verification, I retrieve this image:
![manual_compose](https://github.com/takahirom/roborazzi/assets/10128377/3c2bb0cb-4820-45eb-9db1-c51b71923bc1)

Updating the test to add padding to the Text composable and running in verification mode, the same test still passes!
After recording new screenshots, the screenshot generated for the manualCompose test is as follows:
![manual_compose 2](https://github.com/takahirom/roborazzi/assets/10128377/0709527d-6e42-40c5-b12a-cfb156f39575)

Is this expected behaviour or should the test fail? How would I make the test fail if it is expected behaviour.

```kotlin
@Test
  fun captureComposeLambdaImage() {
    captureRoboImage("$DEFAULT_ROBORAZZI_OUTPUT_DIR_PATH/manual_compose.png") {
      Box(modifier = Modifier.size(400.dp)) {
        Text("Hello Compose!", modifier = Modifier.padding(100.dp))
      }
    }
}
```

**Comment by takahirom** [comment]
Could you try setting the RoborazziOptions.CompareOptions.changeThreshold to 0 and see if it detects the change? I believe the default value should be 0 to ensure accurate test results. I'll raise this as an issue. 👀

**Comment by CSawczukBBCExt** [comment]
The issue seems to be the `0.01f` threshold, which in the example above is working exactly as expected.

Whilst trying to understand the issue, we stumbled across `SimpleImageComparator` which has a  threshold passed to it which it uses to determine if a pixel is different enough to warrant be marked as different.

Our understanding is that when Roborazzi verifies differences between a source image and an actual image, it'll use the `ImageComparator` implementation to count how many differences there are, and then it will use the `CompareOptions` to determine how many pixels as a percentage of pixels from the entire image has changed, based on the `changeThreshold` field.

The reason we started looking at `changeThreshold` was due to rendering differences (seemingly around alpha blending) between a Mac host and a Linux host. If we could tweak the `SimpleImageComparator` threshold, we should be able to use a `changeThreshold` of 0 and then experience test failures only when there are layout differences, rather than due to minor colour differences.
