### ISSUE TITLE
Prepare a sample using Showkase.

### ISSUE THREAD

**Issue by takahirom** [takahirom/roborazzi#19]
I tried it and Roborazzi apparently works properly with Showkase.

**Comment by jmartinesp** [comment]
I tried replacing Paparazzi with Roborazzi in our codebase and use the metadata generated by Showkase, but I couldn't find a way to automatically run a test for each preview item since the compose test rules only allows calls to `setContent` once per test case and we can't use `TestParameterInjectors` to create those automatically.

Since you were investigating how to combine then, I wanted to ask if there is any other way ro use Roborazzi with Showkase than manually creating a test for each preview item?

**Comment by takahirom** [comment]
I believe that `AndroidJUnit4` is not compatible with `TestParameterInjectors`. Therefore, when I encountered this issue, I decided to remove it and use a standard parameterized test instead.

**Comment by jmartinesp** [comment]
Actually, using parameterized tests with `@RunWith(ParameterizedRobolectricTestRunner::class)` did the trick. Thanks!

**Comment by morux2** [comment]
Hello @takahirom !

I tried showkase with roborazzi in my sample project. Please feel free to use it as a reference.
https://github.com/morux2/RoborazziPractice/pull/3

**Comment by takahirom** [comment]
@morux2 Thanks!
