### ISSUE TITLE
Screenshot tests are not stable

### ISSUE THREAD

**Issue by lihenggui** [takahirom/roborazzi#193]
** Roborazzi version: 
1.6.0

** Background:
I updated the screenshot tests in [this PR](https://github.com/lihenggui/blocker/pull/461), [GitHub actions link](https://github.com/lihenggui/blocker/actions/runs/6650281903/job/18070133145).
The tests ran successfully and updated the existing screenshot in the commit (https://github.com/lihenggui/blocker/pull/461/commits/f4d7804ecc29e3536f4543b54418d22f5b2ce060).

After merging the PR into the main branch, the tests will run again. However, this time they failed due to verification issues. It is worth noting that I did not modify the screenshot; it worked fine in the PR but failed on the main branch, indicating instability or inconsistency.
```
com.merxury.blocker.core.designsystem.SegmentedButtonsScreenshotTests > blockerSegmentedButtons_multipleThemes FAILED
    java.lang.AssertionError at SegmentedButtonsScreenshotTests.kt:43

com.merxury.blocker.core.designsystem.SegmentedButtonsScreenshotTests > blockerOutlineButton_multipleThemes FAILED
    java.lang.AssertionError at SegmentedButtonsScreenshotTests.kt:60

```
GitHub Action link: https://github.com/lihenggui/blocker/actions/runs/6655600282/job/18088005415.

** Expected:
Since no files changed, tests should run normally regardless of whether it is on the main branch or a PR.

**Comment by lihenggui** [comment]
I updated screenshots in a separate pull request by modifying a piece of code. I'm not sure why the changes aren't being detected and included in the previous commit. 
https://github.com/lihenggui/blocker/pull/462

**Comment by takahirom** [comment]
Thank you for bringing this to my attention. I noticed that the task was skipped. This might be an issue related to caching. Regarding the output directory, we have an option to handle it."
<img width="582" alt="image" src="https://github.com/takahirom/roborazzi/assets/1386930/b6e5b53a-f492-45d0-b9ab-a6c450d04896">
<img width="561" alt="image" src="https://github.com/takahirom/roborazzi/assets/1386930/8821625c-ea4b-4066-8368-c9de945116b4">
I have created a Pull Request to set the outputDir parameter in order to address the caching issue.
https://github.com/lihenggui/blocker/pull/463
We have some tests in place to check the cache, but I am not entirely confident if the option is functioning as expected.
https://github.com/takahirom/roborazzi/blob/main/include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProjectTest.kt#L56

**Comment by lihenggui** [comment]
Hi @takahirom I have merged this PR and will monitor for any recurrence of this issue.

**Comment by takahirom** [comment]
I've added a document for this. Let me close. Please tell me if you have any issues.
https://github.com/takahirom/roborazzi/blob/f2d7a314ef87555e874947976b731c4d4cea0a38/README.md#q-my-tests-are-being-skipped-or-conversely-are-being-run-when-they-should-be-skipped-how-can-i-handle-caching-to-address-this
