### ISSUE TITLE
Memory leak with Compose screenshot testing

### ISSUE THREAD

**Issue by vetoketju** [takahirom/roborazzi#227]
ActivityScenario is not closed and results in a memory leak where old activities are left.

in RoborazziCompose.kt line 43 the activityScenario should be closed with close() after use.

Some context from Roboelectric:
https://github.com/robolectric/robolectric/issues/7041#issuecomment-1033875547

**Comment by takahirom** [comment]
Thank you for bringing this to our attention. While I don't view this as a critical issue, since developers are likely to implement tests for each Composable, I do recognize that there might be instances where taking screenshots in a single test case is necessary. Moreover, the inability to release memory during testing is problematic. Therefore, I agree that implementing a closure would be beneficial. 

> If you set up an Activity in each test, and forget to close them, it will usually be okay, and the Activity will eventually get GC'd, as Robolectric resets Android state in between each test.
