### ISSUE TITLE
Support overriding of build dir

### ISSUE THREAD

**Issue by dalapenko** [takahirom/roborazzi#265]
At this time in this lib we can override only dir where store golden images throw **outputDirectoryPath** param of **RoborazziRule.Options**, but reports/test-results and outputs of comparing every time save in {app_module}/build/. As example in my project with multi modules we have single point of build dirs in root of project like build/module_build/{module}/{outputs/reports/test_results/} where store all building artefacts. I wanna saved files from robarazzi in this folder too. Now implementation is hardcode with constants dirs. My suggest make this more flexible and support override root of build dir for lib. What do  you think about this?

**Comment by takahirom** [comment]
Thank you for your proposal. I believe it's a convenient idea; however, it may present some difficulties. This is because the reports/test-results/roborazzi/results/ files are utilized for creating a summary file, and merging the folder would prevent us from making a summary file for the module. We could consider making the summary file path customizable. Would that solution work for you?

**Comment by takahirom** [comment]
Got it, we need to make the path in RoborazziReportConst flexible, based on Gradle's build directory settings. This means we'll adjust the paths for test results to match the Gradle configuration, like build/module_build/{module_name}/test-results/roborazzi/results-summary.json. To do this, we need to pass the build directory from Gradle to our tests. I'll explore how we can implement this effectively.
