### ISSUE TITLE
captureScreenRoboImage generates screenshots with top bar 

### ISSUE THREAD

**Issue by victorpineda-jt** [takahirom/roborazzi#315]
This might be a silly question, but I've noticed that `captureScreenRoboImage()` generates a screenshot with a top bar that contains the app name. Is it possible to remove this top bar somehow when using this method?

Thanks in advance.

**Comment by takahirom** [comment]
Thank you for your message. The function captureScreenRoboImage() is designed to capture the entire screen, whereas captureRoboImage() should be used for specific components. To better assist you, I would need to understand more about your use case. Could you please clarify why you are looking to remove the top app bar from the captureScreenRoboImage() function?

**Comment by takahirom** [comment]
I'm not sure, but Material 3's bottom sheet seems [a little different](https://github.com/takahirom/roborazzi/pull/237). Have you tried using Espresso instead of a Compose rule to find the node? It would go something like this, though we need to figure out how to do it.

`onView(????).captureRoboImage()`

https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/androidMain/kotlin/androidx/compose/ui/window/AndroidPopup.android.kt;l=473?q=PopupLayout%20androidx.compose.ui.window

**Comment by takahirom** [comment]
Compose's rule uses ActivityScenario, which is part of Espresso. Therefore, I believe you are already using Espresso, perhaps without realizing it. You should be able to use the onView() method. We might have a solution, so I will close this issue for now. I value our users, so if you have any use cases for this feature and the workaround is insufficient, please let me know. I'll reopen the issue.
