### ISSUE TITLE
Single image support

### ISSUE THREAD

**Issue by mtirimie1** [takahirom/roborazzi#316]
I can't tell if this is possible already and i'm just not seeing it, but is it possible to record a single snapshot at a time? You have the ability to record a whole new set at once, but it'd be helpful to me to be able to focus on the only screen that should have changed

**Comment by takahirom** [comment]
Thanks

If you're looking to run a single test instead of all tests, you might consider these two methods:

* Use the recordRoborazziDebug command with the `--tests` option to specify the test class you want to execute.
* Define your test settings in gradle.properties and use the run button next to the test in Android Studio.

**Comment by takahirom** [comment]
Sorry I forgot to add the link.
https://github.com/takahirom/roborazzi?tab=readme-ov-file#q-how-can-i-debug-screenshot-tests-in-android-studio

**Comment by takahirom** [comment]
I'll close this issue.
If you still have any questions let me know!
