### ISSUE TITLE
Snapshot diff tolerance

### ISSUE THREAD

**Issue by mattinger** [takahirom/roborazzi#324]
I'm looking at replacing paparazzi with roborazzi in some of my projects.  I'm not sure if i'm missing something or not, but is there no way to set a diff tolerance for the verify tasks?  This is something that paparazzi allowed, that seems to be not available in this project.

**Comment by takahirom** [comment]
In `RoborazziOptions`, you can configure `CompareOptions` to set thresholds for change percentage and color distance. Additionally, because it supports the interface from `dropbox/differ`, you can also write your own diff logic. This flexibility allows you to tailor the snapshot comparison to your specific needs.

**Comment by takahirom** [comment]
I'll close this issue now. If you encounter any issues with comparison or verification, please let me know.
