### ISSUE TITLE
Feature request: provide tolerance for the screenshot

### ISSUE THREAD

**Issue by sergio-sastre** [takahirom/roborazzi#4]
Most screenshot testing frameworks provide some “tolerance” factor: the test will still pass even though a given percentage of pixels differ.

Note that this might also happen on JVM tests, for instance, when running them on different Operating Systems
https://github.com/cashapp/paparazzi/issues/311

In fact, Paparazzi’s default tolerance is 0.1 (10% might differ and it would still pass)

**Comment by takahirom** [comment]
https://github.com/takahirom/roborazzi/blob/c7ef27e66d84acd23e8be5a087dc39c2d3e90845/roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt#L408
Thanks for creating issue.
The code is here. 
I will change it to 0.1 for now.
Ideally, it would seem better if users could change it, but do you use it?

**Comment by takahirom** [comment]
I've thought about this. I might take this mistaken.
Should we probably calculate the distance of color instead of the amount of changed pixel count?

**Comment by takahirom** [comment]
> Paparazzi’s default tolerance is 0.1

@sergio-sastre I read a code a bit. Is it 0.01, right?

https://github.com/cashapp/paparazzi/blob/master/paparazzi/paparazzi-gradle-plugin/src/test/java/app/cash/paparazzi/gradle/ImageSubject.kt#L91

**Comment by takahirom** [comment]
Also, unlike Paparazzi, Roborazzi's color may not differ depending on the operating system.

**Comment by takahirom** [comment]
For now, How about changing the default threshold to 0.01?

**Comment by sergio-sastre** [comment]
Hi @takahirom ! I’m on holidays so I’m not checking Github actively.

Yep, it was 0.01. It seems fine to me.

Just implement a solution if somebody opens an issue reporting such a problem.

**Comment by rharter** [comment]
Having done this in Paparazzi and [Dropshots](https://github.com/dropbox/dropshots), I'd expect the rendering to differ between operating systems. There are two levels of variance here, the distance each pixel can be, and also how many pixels can be different. 

In Dropshots, I allowed for customization by letting users [supply their own configured comparator](https://github.com/dropbox/dropshots/blob/978668a7417b879baa9160b3625fd94f476281a3/dropshots/src/main/java/com/dropbox/dropshots/Dropshots.kt#L38) to the rule, and also letting them supply a [custom validator](https://github.com/dropbox/dropshots/blob/978668a7417b879baa9160b3625fd94f476281a3/dropshots/src/main/java/com/dropbox/dropshots/Dropshots.kt#L42) in case they want a different number of pixels that can be different. These both have sensible defaults so that you usually don't have to customize the values, but we do find ourselves having to tweak them from time to time.

**Comment by sergio-sastre** [comment]
Additionally to @rharter comment, Roborazzi has the potential to run either on devices/emulators or on the JVM for screenshot testing by using the AndroidJunit4 TestRunner.
I’d give it a second thought.

Maybe it would makes sense to provide separate pixel validators for each case

**Comment by takahirom** [comment]
> devices/emulators

I think this will require some effort. But interesting

* Create Gradle task for AndroidTest
* Sending and receiving images via adb. Before the test starts, push the image that is currently stored to the device for verify. And pull the results when the test is over.
* Creation of roborazzi-android-painter and roborazzi-awt-painter. We need to abstract the painter. We need to be able to draw to Android Bitmap what we are doing now with BufferedImage.

**Comment by rharter** [comment]
You're describing Dropshots. It's for on-device screenshot testing, and already does all of that. (without adb to send images to device, just modify Gradle to add their folder as a test asset source set)

The reason differ is mpp is so that we could use the exact same image differ in Dropshots (on device) and Paparazzi (junit tests).

**Comment by takahirom** [comment]
I did not realize that you are the one who makes the Dropshot library.
What I was thinking is whether the call captureRoboImage() should be shared and usable by both AndroidTest and JVM tests.
However, I am a bit skeptical about how common and practical it is to share tests at this point.
Also, users could use something like Testing Robot Pattern to hide the library that takes that screenshot.
However, being able to do so does not inhibit the user in any way, so it may be more convenient to do so.

**Comment by sergio-sastre** [comment]
> Also, users could use something like Testing Robot Pattern to hide the library that takes that screenshot.

That’s definitely not as simple as you think.
Each screenshot testing library provides its:
- own library configuration.
- own way to define device configuration (e.g Locale, UiMode, FontScale…) if not missing that at all
- own TestRule for screenshooting.
- own peculiarities (e.g Robolectric needs a TestRunner whose use is incomparable with Paparazzi. Paparazzi dependency cannot be  defined for androidTests because it results in duplicated classes errors… )

I’ve achieved it in AndroidUiTestingUtils 2.0.0-beta01:
https://github.com/sergio-sastre/AndroidUiTestingUtils#library-agnostic-screenshot-tests-beta
I’m planning to add Roborazzi support in beta02 too

If you do not want to consider shared tests at this point, I understand it. Robolectric Graphics mode is still in alpha.

Common? I don’t think many teams use it.

Practical? Well, for teams like mine that implement TDD, getting fast feedback by running tests on the JVM, without sacrificing reliability (running them on a devices on the CI) is crucial. In doing so, we get the best of both worlds.

**Comment by takahirom** [comment]
Now I understand why you want to pass a custom validator instead of a threshold. 
Certainly, the scope of what a library author can develop is limited, so it might make sense to specialize in a certain area and cover it with a library that brings it all together. 
Please let me know if there are other interfaces that are hard to make common in Roborazzi.
