### ISSUE TITLE
[IDE Plugin] Show multiple lines when screenshot filename is long

### ISSUE THREAD

**Issue by takahirom** [takahirom/roborazzi#466]
When we perform BDD or variation tests for configurations, screenshot filenames can be lengthy. However, it's crucial to be able to see the entire filename. Therefore, it would be beneficial to have the ability to view the complete filename, even if it spans multiple lines.
You can debug the IDE plugin by running the `runIde` Gradle task.

**Comment by sanao1006** [comment]
I would like to challenge this task!✋

Is it correct that what we want to do with this task is to display long filenames like the one in the image on multiple lines instead of omitting the filename with “...”? 
<img src="https://github.com/user-attachments/assets/4f3204a1-b753-4bca-961f-b678dc96f456"  width=400>

**Comment by takahirom** [comment]
Yes. That's what I want to do!
I tried it for a bit. But it is a little difficult.
