### ISSUE TITLE
Different captured image format

### ISSUE THREAD

**Issue by ArcaNO93** [takahirom/roborazzi#522]
Hello there
Does Roborazzi support capturing\comparing in other formats rather than PNG (i have a particular interest in webp since it is lighter)?
Thanks

**Comment by takahirom** [comment]
We might need to use the lossless format of WebP if we implement it. We should investigate whether it's compatible with platforms like Mac, Windows, and Linux.
For now, you can try using RGB565 for size reduction.
https://github.com/takahirom/roborazzi/blob/db6faacbcfbff7954cdd43741606bbc6e5bf53d3/include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziOptions.kt#L202

**Comment by ArcaNO93** [comment]
ok thanks
i guess for now its possible just to convert everything from png to webp before comparing and after recording via custom gradle task

**Comment by takahirom** [comment]
I am working on this.

**Comment by ArcaNO93** [comment]
yeah id say lossless would do

**Comment by takahirom** [comment]
I'm considering releasing a feature that allows users to save images in their preferred format. However, there are some challenges. Roborazzi compares a new image with a previously saved one, which means that if the saved image is compressed (e.g., in a format like WebP), image differences might occur, as I mentioned. You can suppress these differences by using high `maxDistance` values, along with `hShift` and `vShift`, to manage this. If you prefer a lossless format, you can provide your own image writer through `IIORegistry`, a feature in Java, although this approach might be slightly complex.

Another way to address this issue is by offering `save BufferedImage` and `load BufferedImage` listeners to users. However, this is a JVM-specific approach, which could be implemented as a platform-specific class within the platform source set like this.
<img width="1335" alt="image" src="https://github.com/user-attachments/assets/b63ceaf8-e713-4c59-adb6-8c97356a880e">


For now, I’m leaning towards implementing the feature that allows users to save images in their preferred format, as I initially mentioned.

**Comment by takahirom** [comment]
I apologize for frequently changing my opinion 😅. I will support lossless WebP, and you can customize both the image writer and loader as previously mentioned.
https://github.com/takahirom/roborazzi/pull/529

**Comment by takahirom** [comment]
@ArcaNO93 If you have time, could you please review this PR?
https://github.com/takahirom/roborazzi/pull/529

**Comment by ArcaNO93** [comment]
oh, ofc

**Comment by ArcaNO93** [comment]
left one comment @takahirom
