### ISSUE TITLE
When RoborazziRule's CaptureType is set to either AllImage or Gif, changes to the ImageView aren't reflected in the screenshot

### ISSUE THREAD

**Issue by colinrtwhite** [takahirom/roborazzi#9]
Setting `ImageView.setDrawable` isn't reflected in the screenshot. [Here's a test](https://github.com/colinrtwhite/NativeGraphicsSample/blob/main/app/src/test/java/com/example/nativegraphicssample/ViewTest.kt) that reproduces the issue. The test updates the image view's drawable to a red box, but the resulting [screenshot is empty](https://github.com/colinrtwhite/NativeGraphicsSample/blob/main/app/src/test/snapshots/images/com.example.nativegraphicssample.ViewTest_test.png). Interestingly, using `imageView.drawToBitmap` renders the red square correctly.

Also is it possible to change the size of the screenshot? Thanks!

**Comment by takahirom** [comment]
Thanks. Perhaps it is because Roborazzi only sees the layout changes.
https://github.com/takahirom/roborazzi/blob/main/roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt#L195

I'll see what I can do about it, but for now it might be a good idea to have it taken with captureRoboImage().
As for image size, I don't think there is a workaround at this time, so I will consider it as soon as possible.
If you don't mind, could you please create an issue on image size?

**Comment by colinrtwhite** [comment]
Using `captureRoboImage` [works great](https://github.com/coil-kt/coil/pull/1685), thanks!

**Comment by takahirom** [comment]
Thanks for your feedback.
I'm working on resize issue 💪 
https://github.com/takahirom/roborazzi/pull/13
